//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldsProject.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FieldService")]
    public interface FieldService {
        
        // CODEGEN: Parameter 'getFieldResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getField", ReplyAction="http://tempuri.org/FieldService/getFieldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FieldsProject.ServiceReference1.getFieldResponse getField(FieldsProject.ServiceReference1.getFieldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getField", ReplyAction="http://tempuri.org/FieldService/getFieldResponse")]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getFieldResponse> getFieldAsync(FieldsProject.ServiceReference1.getFieldRequest request);
        
        // CODEGEN: Parameter 'getAllReservationsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getAllReservations", ReplyAction="http://tempuri.org/FieldService/getAllReservationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FieldsProject.ServiceReference1.getAllReservationsResponse getAllReservations(FieldsProject.ServiceReference1.getAllReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getAllReservations", ReplyAction="http://tempuri.org/FieldService/getAllReservationsResponse")]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllReservationsResponse> getAllReservationsAsync(FieldsProject.ServiceReference1.getAllReservationsRequest request);
        
        // CODEGEN: Parameter 'getAllFieldsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getAllFields", ReplyAction="http://tempuri.org/FieldService/getAllFieldsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FieldsProject.ServiceReference1.getAllFieldsResponse getAllFields(FieldsProject.ServiceReference1.getAllFieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FieldService/getAllFields", ReplyAction="http://tempuri.org/FieldService/getAllFieldsResponse")]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllFieldsResponse> getAllFieldsAsync(FieldsProject.ServiceReference1.getAllFieldsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FieldsProject")]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fieldIDField;
        
        private bool fieldIDFieldSpecified;
        
        private string fieldTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int fieldID {
            get {
                return this.fieldIDField;
            }
            set {
                this.fieldIDField = value;
                this.RaisePropertyChanged("fieldID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldIDSpecified {
            get {
                return this.fieldIDFieldSpecified;
            }
            set {
                this.fieldIDFieldSpecified = value;
                this.RaisePropertyChanged("fieldIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string fieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
                this.RaisePropertyChanged("fieldType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FieldsProject")]
    public partial class Reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private int fieldIDField;
        
        private bool fieldIDFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int fieldID {
            get {
                return this.fieldIDField;
            }
            set {
                this.fieldIDField = value;
                this.RaisePropertyChanged("fieldID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fieldIDSpecified {
            get {
                return this.fieldIDFieldSpecified;
            }
            set {
                this.fieldIDFieldSpecified = value;
                this.RaisePropertyChanged("fieldIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getField", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getFieldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public getFieldRequest() {
        }
        
        public getFieldRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFieldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getFieldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FieldsProject.ServiceReference1.Field getFieldResult;
        
        public getFieldResponse() {
        }
        
        public getFieldResponse(FieldsProject.ServiceReference1.Field getFieldResult) {
            this.getFieldResult = getFieldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllReservations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllReservationsRequest {
        
        public getAllReservationsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllReservationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/FieldsProject")]
        public FieldsProject.ServiceReference1.Reservation[] getAllReservationsResult;
        
        public getAllReservationsResponse() {
        }
        
        public getAllReservationsResponse(FieldsProject.ServiceReference1.Reservation[] getAllReservationsResult) {
            this.getAllReservationsResult = getAllReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFields", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllFieldsRequest {
        
        public getAllFieldsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFieldsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllFieldsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getAllFieldsResult;
        
        public getAllFieldsResponse() {
        }
        
        public getAllFieldsResponse(System.Data.DataTable getAllFieldsResult) {
            this.getAllFieldsResult = getAllFieldsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FieldServiceChannel : FieldsProject.ServiceReference1.FieldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FieldServiceClient : System.ServiceModel.ClientBase<FieldsProject.ServiceReference1.FieldService>, FieldsProject.ServiceReference1.FieldService {
        
        public FieldServiceClient() {
        }
        
        public FieldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FieldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FieldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FieldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FieldsProject.ServiceReference1.getFieldResponse FieldsProject.ServiceReference1.FieldService.getField(FieldsProject.ServiceReference1.getFieldRequest request) {
            return base.Channel.getField(request);
        }
        
        public FieldsProject.ServiceReference1.Field getField(int id) {
            FieldsProject.ServiceReference1.getFieldRequest inValue = new FieldsProject.ServiceReference1.getFieldRequest();
            inValue.id = id;
            FieldsProject.ServiceReference1.getFieldResponse retVal = ((FieldsProject.ServiceReference1.FieldService)(this)).getField(inValue);
            return retVal.getFieldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getFieldResponse> FieldsProject.ServiceReference1.FieldService.getFieldAsync(FieldsProject.ServiceReference1.getFieldRequest request) {
            return base.Channel.getFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getFieldResponse> getFieldAsync(int id) {
            FieldsProject.ServiceReference1.getFieldRequest inValue = new FieldsProject.ServiceReference1.getFieldRequest();
            inValue.id = id;
            return ((FieldsProject.ServiceReference1.FieldService)(this)).getFieldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FieldsProject.ServiceReference1.getAllReservationsResponse FieldsProject.ServiceReference1.FieldService.getAllReservations(FieldsProject.ServiceReference1.getAllReservationsRequest request) {
            return base.Channel.getAllReservations(request);
        }
        
        public FieldsProject.ServiceReference1.Reservation[] getAllReservations() {
            FieldsProject.ServiceReference1.getAllReservationsRequest inValue = new FieldsProject.ServiceReference1.getAllReservationsRequest();
            FieldsProject.ServiceReference1.getAllReservationsResponse retVal = ((FieldsProject.ServiceReference1.FieldService)(this)).getAllReservations(inValue);
            return retVal.getAllReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllReservationsResponse> FieldsProject.ServiceReference1.FieldService.getAllReservationsAsync(FieldsProject.ServiceReference1.getAllReservationsRequest request) {
            return base.Channel.getAllReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllReservationsResponse> getAllReservationsAsync() {
            FieldsProject.ServiceReference1.getAllReservationsRequest inValue = new FieldsProject.ServiceReference1.getAllReservationsRequest();
            return ((FieldsProject.ServiceReference1.FieldService)(this)).getAllReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FieldsProject.ServiceReference1.getAllFieldsResponse FieldsProject.ServiceReference1.FieldService.getAllFields(FieldsProject.ServiceReference1.getAllFieldsRequest request) {
            return base.Channel.getAllFields(request);
        }
        
        public System.Data.DataTable getAllFields() {
            FieldsProject.ServiceReference1.getAllFieldsRequest inValue = new FieldsProject.ServiceReference1.getAllFieldsRequest();
            FieldsProject.ServiceReference1.getAllFieldsResponse retVal = ((FieldsProject.ServiceReference1.FieldService)(this)).getAllFields(inValue);
            return retVal.getAllFieldsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllFieldsResponse> FieldsProject.ServiceReference1.FieldService.getAllFieldsAsync(FieldsProject.ServiceReference1.getAllFieldsRequest request) {
            return base.Channel.getAllFieldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FieldsProject.ServiceReference1.getAllFieldsResponse> getAllFieldsAsync() {
            FieldsProject.ServiceReference1.getAllFieldsRequest inValue = new FieldsProject.ServiceReference1.getAllFieldsRequest();
            return ((FieldsProject.ServiceReference1.FieldService)(this)).getAllFieldsAsync(inValue);
        }
    }
}
