//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class nameEntity
    {
        public nameEntity()
        {
            this.Reservations = new HashSet<ReservationEntity>();
        }
    
        public string name1 { get; set; }
    
        public virtual ICollection<ReservationEntity> Reservations { get; set; }
    }
}
