//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationEntity
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string date { get; set; }
    
        public virtual FieldEntity Field { get; set; }
        public virtual nameEntity name1 { get; set; }
    }
}
